### ISSUE TITLE
Captcha not showing neither on AppImage nor Deb versions of Revolt

### ISSUE THREAD

**Issue by reszkojr** [revoltchat/desktop#37]
When I try to log into Revolt, the captcha doesn't seem to work. Only a button with "Cancel request" shows
![Screenshot_20211004_104519](https://user-images.githubusercontent.com/67809084/135862516-6b3570b6-1875-49f0-ae1c-d45b24f4e3f8.png)

This outputs in the terminal when trying to start both the AppImage and the Deb versions:

```
> $ Downloads/Revolt-1.0.2.AppImage --trace-warnings
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
(node:8120) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/tmp/.mount_Revoltn7JJre/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `revolt-desktop --trace-warnings ...` to show where the warning was created)
(node:8120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The same output is returned from the Deb version.
I'm using Kubuntu 21.10.

**Comment by insertish** [comment]
Haven't had reports of this since, assuming this fixed itself.
